spring.application.name=projetointegrador
spring.datasource.url=jdbc:postgresql://dpg-d8g2103eo5us73808j50-a.ohio-postgres.render.com:5432/rua_minha_jfen
spring.datasource.username=rua_minha_jfen_user
spring.datasource.password=ThIDm6E4i0Yv40NFNprwkhHbaKatjFK3
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

springdoc.swagger-ui.path=/projetointegrador/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true